### PR TITLE
Add skip to toc, update skip to main on standards and about pages

### PR DESCRIPTION
**Pull request by kengdoj**
all pages that use this layout will have a skip to toc added in the header

### CODE REVIEW

**Comment by kengdoj** [comment]
This will fix the skip to TOC/skip to main on the standards and about pages, but in the federalist build, there were 2 scroll bars on the right. I'm assuming that is not intended so I'm holding off merging this.

**Comment by kengdoj** [comment]
Closes Issue #377

**Comment by bruce-usab** [comment]
Thanks Kathy!

**Review by bruce-usab — COMMENTED** [review]
Looks good!

**Pull request closed without merging**
