### PR TITLE
Create News “2020-11-16-u-s-access-board-launches-new-website”

### PR DESCRIPTION
**Pull request by philbratta**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by bruce-usab** [comment]
Phil, please let me know if you get this message.  I am testing to see if Netlify passes along GitHub comments without my putting in your GitHub user ID.  Image file names should be short and cannot use spaces.

**Comment by philbratta** [comment]
Yes, I got this message. I will change the name of the image file and reupload.

Thanks.


---
Phil Bratta, Ph.D.
Technical Writer, Office of Technical and Information Services
U.S. Access Board
(202) 272-0012 (v); (202) 272-0072 (TTY)
bratta@access-board.gov<mailto:bratta@access-board.gov>
www.access-board.gov<http://www.access-board.gov/>

**Comment by bruce-usab** [comment]
Thanks @philbratta 

FWIW, I don't recommend using the reply-via-email feature.  It exposes your email addy to extra spam.

**Comment by philbratta** [comment]
You're welcome. And thanks for the advice. I'll not use the feature.

**Comment by philbratta** [comment]
@bruce-usab Is there any way I can preview posts in Netlify before they go in the queue or live? The excerpt for this news post isn't long enough and the image is too large. Thus, I'll need to go back in, make edits, and resend to the queue. By previewing it, I would be able to save you and Randall time (and perhaps an albatross).

**Comment by bruce-usab** [comment]
@philbratta YES

Is this a page your are getting in your usual workflow?
https://federalistapp.18f.gov/sites/852/builds

Look for entries starting with `cms/posts`
After those are built, there will be `Preview site` link

**Pull request merged**
