### PR TITLE
ICT preamble tables and headings

### PR DESCRIPTION
**Pull request by kengdoj**
table 3 overlaps the TA side bar. all my attempts to change width of table 3 didn't work. sad.

### CODE REVIEW

**Comment by kengdoj** [comment]
Issue #138

**Review by bruce-usab — APPROVED** [review]
Nothing I can't live with!

Thanks for your work!

**Comment by bruce-usab** [comment]
It is because of the text being too long.  I am going to try adding a &shy; to the word "telecommunications"

**Comment by bruce-usab** [comment]
Don't be sad.  The `&shy;` did the trick.

I love all the headers=... code you inserted.  That must have been a labor of love!

**Pull request merged**
