### PR TITLE
Update members.html

### PR DESCRIPTION
**Pull request by bruce-usab**
Delete /images/ from between {{ site.baseurl }} and {{ member.image-file }}

### CODE REVIEW

**Comment by bruce-usab** [comment]
This fixes bug with Board Member images not loading when using GitHub preview.  I added {{ site.baseurl }} in a few places.

**Review by RSD-accessboard — APPROVED** [review]
I'm surprised my build was still working with an extra/images/in there

The

Before the board there were photos I had to in-line style to get it to expand the whole length, we should revisit this.

**Comment by bruce-usab** [comment]
That was my old members.html page, not your new one.

**Comment by bruce-usab** [comment]
It was adding {{ site.baseurl }} to your index.html that made the difference.  Took me a little bit to figure out what was doing what!

**Pull request merged**
