### PR TITLE
Skip to TOC and main content area - enhanced ada

### PR DESCRIPTION
**Pull request by kengdoj**
Created layout files for skip links (defaulttoc and basetoc) and include header2.

Updated standards-enhanced.html only so far. I'll need to look for the other files to add these updated references and will do separate PR for them.

### CODE REVIEW

**Comment by kengdoj** [comment]
Issue #377

**Comment by RSD-accessboard** [comment]
Will call you to talk about this one

**Review by bruce-usab — COMMENTED** [review]
Looks good to me, but pls wait for @RSD-accessboard feedback.

**Comment by kengdoj** [comment]
@bruce-usab said he and @RSD-accessboard are good with this

**Pull request merged**
